import type { Metadata } from "next";
import "./globals.css";
import ClientRoot from "@/components/ClientRoot";

const geistSans = {
  variable: "--font-geist-sans"
};
const geistMono = {
  variable: "--font-geist-mono"
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ClientRoot>{children}</ClientRoot>
      </body>
    </html>
  );
}
